/**
 * Generates seed/00_policies_and_agents.sql from the TypeScript sources of
 * truth (@wiwaha/policy defaults + the agent roster), so the policy book in
 * the database and the typed loader can never drift apart.
 *   pnpm --filter @wiwaha/db gen:seed
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DEFAULT_POLICIES } from "@wiwaha/policy";
import { AGENT_ROSTER } from "../src/roster";

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, "..", "supabase", "seed", "00_policies_and_agents.sql");

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const lines: string[] = [
  "-- GENERATED by packages/db/scripts/gen-seed.ts — do not edit by hand.",
  "-- Policy book defaults (handoff §3 + PRD) and the 21-agent roster (PRD §8).",
  "-- Re-running is safe: existing rows are left alone so owner edits survive.",
  "",
  "insert into public.policies (key, topic, title, rule_text, value, client_visible, needs_confirmation, sort) values",
  DEFAULT_POLICIES.map(
    (p) => `  (${q(p.key)}, ${q(p.topic)}, ${q(p.title)}, ${q(p.rule_text)}, ${j(p.value)}, ${p.client_visible}, ${p.needs_confirmation}, ${p.sort})`,
  ).join(",\n"),
  "on conflict (key) do nothing;",
  "",
  "insert into public.agents (key, name, vertical, job, human_gate, phase, implemented, enabled, autonomy, model) values",
  AGENT_ROSTER.map(
    (a) =>
      `  (${q(a.key)}, ${q(a.name)}, ${q(a.vertical)}, ${q(a.job)}, ${q(a.humanGate)}, ${a.phase}, true, true, 'draft', ${q(a.model)})`,
  ).join(",\n"),
  "on conflict (key) do nothing;",
  "",
];

writeFileSync(out, lines.join("\n"));
console.log(`wrote ${out}`);
